### PR TITLE
Enable unified_mode for Chef 17

### PR DESCRIPTION
**Pull request by detjensrobert**
Also includes Cookstyle fixes and file cleanup.

### CODE REVIEW

**Review by ramereth — APPROVED** [review]
Major bump please.

**Comment by ramereth** [comment]
Keep in mind you'll need to also bump osl-ceph when you do that

**Comment by detjensrobert** [comment]
!bump major ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v4.0.0.  Have a nice day!

**Pull request merged**
